services:
  nginx:
    image: nginx:latest
    # shouldn't need an exposed port when done
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always
  tor:
    build:
      context: .
      dockerfile: containers/tor/Dockerfile
      # todo: make the hidden service details persist
      # volumes:
        # - ./tor:/var/lib/tor
    restart: always
    depends_on:
      - nginx

